# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbillboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='messages',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
